# -*- coding: utf-8 -*-
"""Population.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16D8awlkfjtAvZQ0EM3PpblHqxG_wTgTL
"""

import pandas as pd
import pandas as pd

pop = pd.read_csv('Population.csv', encoding = 'unicode_escape', index_col=0)

pop.head()

pop.tail()

pop.columns

pop.info()

pop.describe()

! pip install pandas==0.25

from pandas_profiling import ProfileReport

profile = ProfileReport(pop)
profile

pop['City'] = pop['City'].astype(str)

pop['State'] = pop['State'].astype(str)

pop.dtypes

pop.info()

from google.colab import files

pop.to_csv('Population_new.csv')
files.download('Population_new.csv')